// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOUrwOptOtCZVe970KRZ_VK_KQztKbNdU',
    appId: '1:688784599776:web:1f6f96c273236c976a3e85',
    messagingSenderId: '688784599776',
    projectId: 'converter-3c9c6',
    authDomain: 'converter-3c9c6.firebaseapp.com',
    databaseURL: 'https://converter-3c9c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'converter-3c9c6.appspot.com',
    measurementId: 'G-E91E11E49Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnz5EaQZkU3BoGC6CV-E1lXFNInQAikaM',
    appId: '1:688784599776:android:94634e4b3ab2e2f26a3e85',
    messagingSenderId: '688784599776',
    projectId: 'converter-3c9c6',
    databaseURL: 'https://converter-3c9c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'converter-3c9c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo9lZsxcHZhGBK-RXAGea_fEZL-vARWc4',
    appId: '1:688784599776:ios:69257031fc0d9a8c6a3e85',
    messagingSenderId: '688784599776',
    projectId: 'converter-3c9c6',
    databaseURL: 'https://converter-3c9c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'converter-3c9c6.appspot.com',
    iosBundleId: 'com.example.unitConversion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo9lZsxcHZhGBK-RXAGea_fEZL-vARWc4',
    appId: '1:688784599776:ios:69257031fc0d9a8c6a3e85',
    messagingSenderId: '688784599776',
    projectId: 'converter-3c9c6',
    databaseURL: 'https://converter-3c9c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'converter-3c9c6.appspot.com',
    iosBundleId: 'com.example.unitConversion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOUrwOptOtCZVe970KRZ_VK_KQztKbNdU',
    appId: '1:688784599776:web:6feebac5b7be87f16a3e85',
    messagingSenderId: '688784599776',
    projectId: 'converter-3c9c6',
    authDomain: 'converter-3c9c6.firebaseapp.com',
    databaseURL: 'https://converter-3c9c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'converter-3c9c6.appspot.com',
    measurementId: 'G-W3TCY3H4YE',
  );
}
